name: solve15
version: '0.1.0.0'
synopsis: AoC2018
executables:
    solve:
        main: solve.hs
        dependencies:
            - base
            - process
            - containers
            - ilist
            - hspec
            - say
            - lens
            - stm
            - mtl
            - vector
            - set-extra
